import { palette } from './palette';

export const color = {
  palette,
  transparent: 'rgba(0, 0, 0, 0)',
  background: palette.white,
  primary: palette.black,
  darkPrimary: palette.darkBlue,
  lightPrimary: palette.lightBlue,
  border: palette.lightPurple,
  textBlack: palette.black,
  textDark1: palette.dark1,
  textDark2: palette.dark2,
  textDark3: palette.dark3,
  textDark4: palette.dark4,
  error: palette.red,
  link: palette.royalBlue,
  line: palette.linkWater,
  placeholder: palette.grayMid,
  textGray: palette.gray4,
  textLightGray: palette.gray3,
  folderBg: palette.lightCyan4,
  lightGreen: palette.lightGreen,
  green: palette.green,
  shadowColor: palette.black,
  circleBg: palette.softPeach,
  sliderYellow: palette.yellow,
  trackerLightYellow: palette.lightYellow,
  sliderRed: palette.maroon,
  trackerLightRed: palette.lightRed,
  borderBottomGrey: palette.gray5,
  loader: palette.blue,
  overlay: palette.overlay,
  toastErrorBorder: palette.maroon,
  toastErrorBg: palette.lavendraBlush,
  toastSuccessBorder: palette.pearlAqua,
  toastInfoBorder: palette.lightPurple,
  toastInfoBg: palette.lightCyan1,
  darkGrey: palette.gray2,
  choco: palette.mineShaft,
};
